namespace TaxesUa.Api.Tests.Architecture;

// A file past this size mixes concerns a reader has to hold at once (#186). Generated code is exempt:
// *.g.cs files and the EF migrations, whose snapshot and designers carry an auto-generated header and
// are rewritten by `dotnet ef`, not read.
public sealed class SourceSizeTests
{
    private const int MaxLines = 600;

    [Fact]
    public void No_hand_written_source_file_is_over_600_lines()
    {
        var src = Path.Combine(Above(Path.Combine("src", "TaxesUa.Api", "Program.cs")), "src");

        var tooLong = Directory.EnumerateFiles(src, "*.cs", SearchOption.AllDirectories)
            .Where(path => !path.Split(Path.DirectorySeparatorChar).Any(part => part is "bin" or "obj"))
            .Where(path => !path.EndsWith(".g.cs", StringComparison.Ordinal))
            .Select(path => (Path: path, Lines: File.ReadAllLines(path)))
            .Where(file => !file.Lines.Take(5).Any(line => line.Contains("<auto-generated", StringComparison.Ordinal)))
            .Where(file => file.Lines.Length > MaxLines)
            .Select(file => $"{Path.GetRelativePath(src, file.Path)}: {file.Lines.Length} lines")
            .ToArray();

        Assert.True(
            tooLong.Length == 0,
            $"Split along a real seam (a partial class or a cohesive type), at most {MaxLines} lines:\n{string.Join(Environment.NewLine, tooLong)}");
    }

    // The api/ directory above the test binaries.
    private static string Above(string relative)
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, relative)))
            {
                return directory.FullName;
            }
        }

        throw new InvalidOperationException($"{relative} is not above the test binaries.");
    }
}
