// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxesUa.Api.Data;

#nullable disable

namespace TaxesUa.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001163118_AddReserveJar")]
    partial class AddReserveJar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("bytea");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Audit.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("After")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "At");

                    b.HasIndex("UserId", "Entity", "EntityId", "At");

                    b.ToTable("AuditLog", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Snapshots", "(\"Action\" = 'Create' AND \"Before\" IS NULL AND \"After\" IS NOT NULL) OR (\"Action\" = 'Update' AND \"Before\" IS NOT NULL AND \"After\" IS NOT NULL) OR (\"Action\" = 'Delete' AND \"Before\" IS NOT NULL AND \"After\" IS NULL) OR (\"Action\" = 'Restore' AND \"Before\" IS NULL AND \"After\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Calendar.CalendarFeed", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Secret")
                        .IsUnique();

                    b.ToTable("CalendarFeeds");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Declarations.DeclarationFile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<byte[]>("AnnexContent")
                        .HasColumnType("bytea");

                    b.Property<string>("AnnexFileName")
                        .HasColumnType("text");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Year", "Quarter", "Type");

                    b.ToTable("DeclarationFiles", t =>
                        {
                            t.HasCheckConstraint("CK_DeclarationFiles_Annex", "(\"AnnexFileName\" IS NULL) = (\"AnnexContent\" IS NULL)");

                            t.HasCheckConstraint("CK_DeclarationFiles_Quarter", "\"Quarter\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Declarations.DeclarationFiling", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FiledIncomeKop")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("FiledOn")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Year", "Quarter");

                    b.ToTable("DeclarationFilings", t =>
                        {
                            t.HasCheckConstraint("CK_DeclarationFilings_Quarter", "\"Quarter\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Fx.FxRate", b =>
                {
                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<int>("RateE4")
                        .HasColumnType("integer");

                    b.HasKey("Currency", "Date");

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("NumberSequence")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberYear")
                        .HasColumnType("integer");

                    b.Property<string>("SignatureContentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("SignatureImage")
                        .HasColumnType("bytea");

                    b.Property<string>("Snapshot")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId", "IssueDate");

                    b.HasIndex("UserId", "NumberYear", "NumberSequence")
                        .IsUnique()
                        .HasFilter("\"NumberSequence\" IS NOT NULL");

                    b.ToTable("Invoices", t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_Status", "(\"Status\" = 0 AND \"NumberSequence\" IS NULL AND \"Snapshot\" IS NULL AND \"CancelReason\" IS NULL) OR (\"Status\" = 1 AND \"NumberSequence\" IS NOT NULL AND \"Snapshot\" IS NOT NULL AND \"CancelReason\" IS NULL) OR (\"Status\" = 2 AND \"NumberSequence\" IS NOT NULL AND \"Snapshot\" IS NOT NULL AND \"CancelReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Bank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("HistoryImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("SyncedThrough")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Bank", "ExternalId")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.ForeignDebit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BankTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "BankTime");

                    b.ToTable("ForeignDebits");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.MonobankConnection", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("MonobankClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WebhookFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookFailure")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UserId");

                    b.HasIndex("WebhookSecret")
                        .IsUnique();

                    b.ToTable("MonobankConnections");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.ReserveJar", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long>("BalanceKop")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JarId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("UserId");

                    b.ToTable("ReserveJars");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique();

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.NotificationLinkCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLinkCodes");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.SentReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kinds")
                        .HasColumnType("integer");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date", "Kinds", "Offset", "Channel")
                        .IsUnique();

                    b.ToTable("SentReminders");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.TelegramPollState", b =>
                {
                    b.Property<long>("BotId")
                        .HasColumnType("bigint");

                    b.Property<long>("NextOffset")
                        .HasColumnType("bigint");

                    b.HasKey("BotId");

                    b.ToTable("TelegramPollStates");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.BudgetPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKop")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<int?>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("PeriodQuarter")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "PeriodYear");

                    b.ToTable("BudgetPayments", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPayments_AmountKop", "\"AmountKop\" > 0");

                            t.HasCheckConstraint("CK_BudgetPayments_BankOperation", "(\"BankAccountId\" IS NULL) = (\"ExternalId\" IS NULL)");

                            t.HasCheckConstraint("CK_BudgetPayments_OnePeriod", "(\"PeriodQuarter\" IS NULL) <> (\"PeriodMonth\" IS NULL)");

                            t.HasCheckConstraint("CK_BudgetPayments_PeriodMonth", "\"PeriodMonth\" IS NULL OR \"PeriodMonth\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("CK_BudgetPayments_PeriodQuarter", "\"PeriodQuarter\" IS NULL OR \"PeriodQuarter\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.BudgetPaymentCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKop")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BankTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedKind")
                        .HasColumnType("integer");

                    b.Property<string>("CounterEdrpou")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CounterIban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("CounterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("BudgetPaymentCandidates", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetPaymentCandidates_AmountKop", "\"AmountKop\" > 0");

                            t.HasCheckConstraint("CK_BudgetPaymentCandidates_ConfirmedKind", "(\"Status\" = 1) = (\"ConfirmedKind\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.TreasuryAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LearnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnedExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LearnedIban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<DateOnly?>("LearnedPaidOn")
                        .HasColumnType("date");

                    b.Property<string>("LearnedRecipientCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("LearnedRecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ManualIban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("ManualRecipientCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ManualRecipientName")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<DateTimeOffset?>("ManualUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NoticeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind")
                        .IsUnique();

                    b.ToTable("TreasuryAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_TreasuryAccounts_Learned", "(\"LearnedIban\" IS NULL) = (\"LearnedExternalId\" IS NULL) AND (\"LearnedIban\" IS NULL) = (\"LearnedPaidOn\" IS NULL) AND (\"LearnedIban\" IS NULL) = (\"LearnedAt\" IS NULL) AND (\"LearnedIban\" IS NOT NULL OR (\"LearnedRecipientName\" IS NULL AND \"LearnedRecipientCode\" IS NULL))");

                            t.HasCheckConstraint("CK_TreasuryAccounts_Manual", "(\"ManualIban\" IS NULL) = (\"ManualRecipientName\" IS NULL) AND (\"ManualIban\" IS NULL) = (\"ManualRecipientCode\" IS NULL) AND (\"ManualIban\" IS NULL) = (\"ManualUpdatedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_TreasuryAccounts_Notice", "\"NoticeAt\" IS NULL OR (\"ManualIban\" IS NOT NULL AND \"LearnedIban\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.DeclarationDetails", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("KvedCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("TaxOfficeDistrict")
                        .HasColumnType("integer");

                    b.Property<string>("TaxOfficeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TaxOfficeRegion")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("DeclarationDetails", t =>
                        {
                            t.HasCheckConstraint("CK_DeclarationDetails_TaxOffice", "(\"TaxOfficeRegion\" IS NULL) = (\"TaxOfficeDistrict\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.InvoicingDetails", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AcceptanceClauseEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcceptanceClauseUk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressUk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeesClauseEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeesClauseUk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rnokpp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SellerNameUk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignatureContentType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("SignatureImage")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("SignatureUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxStatusClauseEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxStatusClauseUk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("InvoicingDetails");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.InvoicingPaymentDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BeneficiaryBank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntermediaryAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntermediaryBank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntermediarySwift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Swift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Currency")
                        .IsUnique();

                    b.ToTable("InvoicingPaymentDetails");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.Settings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int?>("BackOnGroup3FromQuarter")
                        .HasColumnType("integer");

                    b.Property<int?>("BackOnGroup3FromYear")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsvExempt")
                        .HasColumnType("boolean");

                    b.Property<int>("EsvRegistrationMonthPolicy")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FopRegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<bool>("ShiftTaxPaymentFromWeekend")
                        .HasColumnType("boolean");

                    b.Property<bool>("TaxPaymentCountsFromStatutoryDeclarationDate")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("WeekendDays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("UserId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.TaxYears.TaxYearConfig", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("AdvanceRecommendedDay")
                        .HasColumnType("integer");

                    b.Property<int>("DeclarationDays")
                        .HasColumnType("integer");

                    b.Property<int>("EsvDeadlineDay")
                        .HasColumnType("integer");

                    b.Property<long>("EsvMonthlyKop")
                        .HasColumnType("bigint");

                    b.Property<int>("EsvRateBp")
                        .HasColumnType("integer");

                    b.Property<int>("ExcessRateBp")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<DateOnly[]>("Holidays")
                        .IsRequired()
                        .HasColumnType("date[]");

                    b.Property<long>("IncomeLimitKop")
                        .HasColumnType("bigint");

                    b.Property<int>("IncomeLimitMinWages")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("LimitWarnThresholdsPct")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("MilitaryLevyRateBp")
                        .HasColumnType("integer");

                    b.Property<long>("MinWageKop")
                        .HasColumnType("bigint");

                    b.Property<int>("SingleTaxRateBp")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaxPaymentDaysAfterDeclaration")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Year");

                    b.ToTable("TaxYearConfigs");

                    b.HasData(
                        new
                        {
                            Year = 2026,
                            AdvanceRecommendedDay = 15,
                            DeclarationDays = 40,
                            EsvDeadlineDay = 19,
                            EsvMonthlyKop = 190234L,
                            EsvRateBp = 2200,
                            ExcessRateBp = 1500,
                            Holidays = new DateOnly[0],
                            IncomeLimitKop = 1009104900L,
                            IncomeLimitMinWages = 1167,
                            LimitWarnThresholdsPct = new[] { 85, 100 },
                            MilitaryLevyRateBp = 100,
                            MinWageKop = 864700L,
                            SingleTaxRateBp = 500,
                            Source = "ЗУ «Про Держбюджет України на 2026 рік»; ПКУ ст. 293, 295, 296; ЗУ «Про ЄСВ» ст. 8",
                            TaxPaymentDaysAfterDeclaration = 10
                        });
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int?>("DefaultCurrency")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VatId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BankAccountId", "CreatedAt");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountUahKop")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("BankTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Counterparty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("NonIncomeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("RateDate")
                        .HasColumnType("date");

                    b.Property<int>("RateE4")
                        .HasColumnType("integer");

                    b.Property<int?>("RateSource")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RefundsTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("RefundsTransactionId");

                    b.HasIndex("BankAccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId", "ValueDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Calendar.CalendarFeed", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Declarations.DeclarationFile", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Declarations.DeclarationFiling", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Invoices.Invoice", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Transactions.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.BankAccount", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.ForeignDebit", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Monobank.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.MonobankConnection", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TaxesUa.Api.Features.Monobank.MonobankConnection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Monobank.ReserveJar", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TaxesUa.Api.Features.Monobank.ReserveJar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.NotificationChannel", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.NotificationLinkCode", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Notifications.SentReminder", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.BudgetPayment", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Monobank.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.BudgetPaymentCandidate", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Monobank.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Payments.TreasuryAccount", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.DeclarationDetails", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TaxesUa.Api.Features.Settings.DeclarationDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.InvoicingDetails", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TaxesUa.Api.Features.Settings.InvoicingDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.InvoicingPaymentDetails", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Settings.Settings", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("TaxesUa.Api.Features.Settings.Settings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.Client", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.ImportBatch", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Monobank.BankAccount", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaxesUa.Api.Features.Transactions.Transaction", b =>
                {
                    b.HasOne("TaxesUa.Api.Features.Monobank.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaxesUa.Api.Features.Transactions.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxesUa.Api.Features.Transactions.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TaxesUa.Api.Features.Invoices.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxesUa.Api.Features.Transactions.Transaction", "RefundsTransaction")
                        .WithMany()
                        .HasForeignKey("RefundsTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxesUa.Api.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("Client");

                    b.Navigation("Invoice");

                    b.Navigation("RefundsTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
