// Builds KvedClasses.g.cs from Держстат's classifier pages: every class of КВЕД ДК 009:2010 and its
// official name, the <p class="Na"> text of KVED2010/{dd}/KVED10_{dd}_{cc}.html, as published.
// Run from the repository root: node api/tools/build-kved.mjs

import { writeFile } from "node:fs/promises";

const origin = "https://kved.ukrstat.gov.ua";
const output = new URL("../src/TaxesUa.Api/Features/Declarations/KvedClasses.g.cs", import.meta.url);
const decoder = new TextDecoder("windows-1251");

async function page(path) {
  for (let attempt = 1; ; attempt++) {
    try {
      const response = await fetch(origin + path, { signal: AbortSignal.timeout(30_000) });
      if (!response.ok) {
        throw new Error(`${path}: HTTP ${response.status}`);
      }
      return decoder.decode(await response.arrayBuffer());
    } catch (error) {
      if (attempt === 4) {
        throw error;
      }
      await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
    }
  }
}

function links(html, pattern) {
  return [...new Set([...html.matchAll(/href="([^"]+)"/g)].map((match) => match[1]).filter((href) => pattern.test(href)))];
}

const entities = { quot: '"', amp: "&", lt: "<", gt: ">", apos: "'", nbsp: " " };

function text(html) {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (entity, name) =>
      name.startsWith("#")
        ? String.fromCodePoint(name[1].toLowerCase() === "x" ? parseInt(name.slice(2), 16) : Number(name.slice(1)))
        : (entities[name.toLowerCase()] ?? entity),
    )
    .replace(/\s+/g, " ")
    .trim();
}

async function mapLimited(items, limit, work) {
  const results = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: limit }, async () => {
      while (next < items.length) {
        const index = next++;
        results[index] = await work(items[index]);
      }
    }),
  );
  return results;
}

const sections = links(await page("/KVED2010/kv10_i.html"), /^\/KVED2010\/SECT\/KVED10_[A-U]\.html$/);
const divisions = (await mapLimited(sections, 4, async (path) => links(await page(path), /^\/KVED2010\/\d{2}\/KVED10_\d{2}\.html$/))).flat();
const groups = (await mapLimited([...new Set(divisions)], 4, async (path) => links(await page(path), /^\/KVED2010\/\d{2}\/KVED10_\d{2}_\d\.html$/))).flat();
const classPaths = (await mapLimited([...new Set(groups)], 4, async (path) => links(await page(path), /^\/KVED2010\/\d{2}\/KVED10_\d{2}_\d{2}\.html$/))).flat();

const classes = await mapLimited([...new Set(classPaths)].sort(), 4, async (path) => {
  const [, division, cls] = path.match(/KVED10_(\d{2})_(\d{2})\.html$/);
  const names = [...(await page(path)).matchAll(/<p class="Na">([\s\S]*?)<\/p>/g)].map((match) => text(match[1]));
  if (names.length !== 1 || names[0] === "") {
    throw new Error(`${path}: expected one class name, found ${names.length}`);
  }
  return { code: `${division}.${cls}`, name: names[0] };
});

const divisionCount = new Set(classes.map(({ code }) => code.slice(0, 2))).size;
if (classes.length !== 615 || divisionCount !== 88) {
  throw new Error(`КВЕД ДК 009:2010 has 615 classes in 88 divisions; the site gave ${classes.length} in ${divisionCount}`);
}

const csharp = (value) => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

await writeFile(
  output,
  [
    "// <auto-generated>",
    "// Built by api/tools/build-kved.mjs from https://kved.ukrstat.gov.ua/KVED2010/kv10_i.html.",
    "// Rerun the script instead of editing this file.",
    "// </auto-generated>",
    "",
    "namespace TaxesUa.Api.Features.Declarations;",
    "",
    "internal static partial class Kved",
    "{",
    "    private static readonly Dictionary<string, string> Names = new(StringComparer.Ordinal)",
    "    {",
    ...classes.map(({ code, name }) => `        [${csharp(code)}] = ${csharp(name)},`),
    "    };",
    "}",
    "",
  ].join("\n"),
);

console.log(`${classes.length} classes written to ${output.pathname}`);
