using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TaxesUa.Api.Features.TaxYears;

internal sealed class TaxYearConfigConfiguration : IEntityTypeConfiguration<TaxYearConfig>
{
    public void Configure(EntityTypeBuilder<TaxYearConfig> builder)
    {
        builder.HasKey(config => config.Year);

        // EF makes an int key identity-generated by convention, and the year is always supplied.
        builder.Property(config => config.Year).ValueGeneratedNever();

        builder.HasData(Seed2026());
    }

    // The values come from Rule 3, Rule 4 and Rule 5 of knowledge/business-rules.md. The derived pair
    // is recomputed here so no migration carries a figure that was typed by hand.
    private static TaxYearConfig Seed2026()
    {
        var config = new TaxYearConfig
        {
            Year = 2026,
            MinWageKop = 864_700,
            SingleTaxRateBp = 500,
            MilitaryLevyRateBp = 100,
            EsvRateBp = 2200,
            ExcessRateBp = 1500,
            IncomeLimitMinWages = 1167,
            LimitWarnThresholdsPct = [85, 100],
            EsvDeadlineDay = 19,
            DeclarationDays = 40,
            TaxPaymentDaysAfterDeclaration = 10,
            AdvanceRecommendedDay = 15,

            // Rule 5: martial law makes holidays business days, so the list is empty rather than
            // unknown.
            Holidays = [],
            Source = "ЗУ «Про Держбюджет України на 2026 рік»; ПКУ ст. 293, 295, 296; ЗУ «Про ЄСВ» ст. 8",

            // Spelled out because it is a decision, not an omission: nobody has checked these values
            // against the law, and Rule 9's warning only means something if the seed starts unverified.
            VerifiedAt = null,
        };

        config.RecomputeDerived();
        return config;
    }
}
